# Generated by Django 4.1.5 on 2023-01-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='information',
            fields=[
                ('ip', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('org', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Info',
            },
        ),
    ]
