# Generated by Django 4.1.5 on 2023-01-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shodanjangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='city',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AlterField(
            model_name='information',
            name='country',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AlterField(
            model_name='information',
            name='ip',
            field=models.CharField(default='SOME STRING', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='information',
            name='org',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AlterField(
            model_name='information',
            name='os',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
