# Generated by Django 4.1.5 on 2023-02-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shodanjangoapp', '0002_alter_information_city_alter_information_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Address',
            },
        ),
        migrations.AlterField(
            model_name='information',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='information',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='information',
            name='ip',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='information',
            name='org',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='information',
            name='os',
            field=models.CharField(default='', max_length=100),
        ),
    ]
