# Generated by Django 4.1.5 on 2023-02-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shodanjangoapp', '0004_alter_address_ip_alter_information_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='ip',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='information',
            name='ip',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
    ]
