# Generated by Django 4.1.5 on 2023-02-12 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shodanjangoapp', '0005_alter_address_ip_alter_information_ip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='address',
        ),
    ]
